version: "3"

services:
  server:
    container_name: "lamp-server"
    image: ieeeihuserres/lamp-dockerized:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/home/user/vhosts
      - ./ssl:/home/user/ssl
    depends_on:
      - database
    networks:
      - lamp-network

  database:
    container_name: "lamp-database"
    image: bitnami/mariadb:10.3
    restart: always
    environment:
      - MARIADB_ROOT_USER=${DATABASE_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MARIADB_USER=${DATABASE_USERNAME}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_DATABASE=${DATABASE_NAME}
    networks:
      - lamp-network
    volumes:
      - ./database:/bitnami/mariadb

  phpmyadmin:
    container_name: "lamp-phpmyadmin"
    image: bitnami/phpmyadmin:4.9.2
    restart: always
    ports:
      - 1081:80
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT_NUMBER=3306
    depends_on:
      - database
    networks:
      - lamp-network
    volumes:
      - ./phpmyadmin:/bitnami/phpmyadmin

networks:
  lamp-network: